spring.application.name=order-service
server.port=8086
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#product-service.base-url=${PRODUCT_SERVICE_URL}
spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=afmuzfeu
spring.rabbitmq.password=cYVLgLw9jUSkBYtpRB4Og7HV_VXxdFEr
spring.rabbitmq.virtual-host=afmuzfeu
spring.rabbitmq.ssl.enabled=true
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_URL}/auth/jwks
server.forward-headers-strategy=framework
